language: python
python:
  - "3.8"
cache:
  directories:
    - $HOME/.cache/pip

before_install:
- set -e
- python3 --version
- sudo apt-get install python3-pip
# - pip3 install -r requirements.txt
# - pip3 install --index-url https://test.pypi.org/simple/ --upgrade setuptools pip btrccts
- pip3 install --upgrade setuptools pip btrccts
# Run algo to see all needed requirements are here
- python3 examples/print_time.py --start-date 2017-01-01 --end-date 2017-01-02
